// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// SPDX-License-Identifier: MIT

"use client";

import { useState } from "react";
import { AlertCircle, Check, Loader2, ShieldAlert, ThumbsDown, ThumbsUp } from "lucide-react";
import { toast } from "sonner";

import { Button } from "~/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Label } from "~/components/ui/label";
import { RadioGroup, RadioGroupItem } from "~/components/ui/radio-group";
import { useResumeWorkflow } from "~/core/api/hooks/useWorkflow";
import type { AVLFeedback, RunResumeRequest } from "~/core/api/models/workflow";

import type { BaseInteractionProps } from "./types";

interface AvlCritique {
  id: string;
  critique: string;
  suggestion?: string;
}

type AvlAdjudication = "ACCEPT" | "REJECT";

const parseAvlCritiques = (interaction: BaseInteractionProps["interaction"]): AvlCritique[] => {
  const critiques = (interaction.content_for_review?.critiques || interaction.metadata?.critiques) as unknown;

  if (Array.isArray(critiques)) {
    return critiques.filter(
      (item): item is AvlCritique =>
        typeof item === "object" &&
        item !== null &&
        typeof item.id === "string" &&
        typeof item.critique === "string",
    );
  }

  return [];
};

/**
 * AVL (Adversarial Validation Loop) interaction component.
 * Implements itemized adjudication with global decision serialization.
 */
export const AvlInteraction = ({ interaction, projectId, checkpointId }: BaseInteractionProps) => {
  const critiques = parseAvlCritiques(interaction);
  const [adjudications, setAdjudications] = useState<Record<string, AvlAdjudication>>({});
  const { mutate: resumeWorkflow, isPending } = useResumeWorkflow();

  const adjudicatedCount = Object.keys(adjudications).length;
  const allAdjudicated = critiques.length > 0 && adjudicatedCount === critiques.length;

  const handleAdjudicationChange = (id: string, decision: AvlAdjudication) => {
    setAdjudications((prev) => ({ ...prev, [id]: decision }));
  };

  const handleCompleteReview = () => {
    if (critiques.length > 0 && !allAdjudicated) {
      toast.warning("Please adjudicate all critiques before continuing.");
      return;
    }

    if (isPending) return;

    const acceptedCritiques = Object.values(adjudications).some((decision) => decision === "ACCEPT");
    const decision = critiques.length === 0 || !acceptedCritiques ? "APPROVE_DRAFT" : "ACCEPT_CRITIQUE";

    const feedback: AVLFeedback = {
      mode: "AVL",
      decision,
      notes: JSON.stringify({ adjudications }),
    };

    const request: RunResumeRequest = {
      client_checkpoint_id: checkpointId,
      feedback,
    };

    resumeWorkflow(
      { projectId, data: request },
      {
        onError: (error) => {
          const errorMessage = (error as Error)?.message || "An unexpected error occurred.";
          if (errorMessage.includes("412") || errorMessage.includes("Precondition Failed")) {
            toast.error("Workflow state mismatch", {
              description: "The workflow state has changed. Please review the updates and try again.",
            });
          } else {
            toast.error("Failed to submit review", {
              description: errorMessage,
            });
          }
        },
      },
    );
  };

  if (critiques.length === 0) {
    return (
      <Card className="mt-6 border-green-500/50 shadow-xl">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-xl font-semibold text-green-700">
            <Check className="h-5 w-5" />
            Adversarial Review (AVL)
          </CardTitle>
          <CardDescription>No critical feedback generated by the adversarial AI. You may proceed.</CardDescription>
        </CardHeader>
        <CardFooter className="flex justify-end border-t bg-muted/30 pt-6">
          <Button
            onClick={() => handleCompleteReview()}
            disabled={isPending}
            className="bg-green-600 text-white hover:bg-green-700 dark:bg-green-700 dark:hover:bg-green-800"
          >
            {isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <ThumbsUp className="mr-2 h-4 w-4" />
            )}
            Approve Draft and Continue
          </Button>
        </CardFooter>
      </Card>
    );
  }

  return (
    <Card className="mt-6 border-indigo-500/50 shadow-xl transition-all duration-300 hover:shadow-2xl">
      <CardHeader>
        <CardTitle className="text-xl font-semibold">Adversarial Review Required (AVL)</CardTitle>
        <CardDescription className="text-sm text-muted-foreground">
          {interaction.instructions ||
            "Please review the critiques below and decide whether to accept (revise) or reject (keep) each one."}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6 px-6 pb-6">
        {critiques.map((critique) => (
          <CritiqueItem
            key={critique.id}
            critique={critique}
            decision={adjudications[critique.id]}
            onChange={(decision) => handleAdjudicationChange(critique.id, decision)}
            disabled={isPending}
          />
        ))}
      </CardContent>
      <CardFooter className="flex items-center justify-between border-t bg-muted/30 pt-6">
        <p className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
          {allAdjudicated ? (
            <Check className="h-4 w-4 text-green-500" />
          ) : (
            <AlertCircle className="h-4 w-4 text-amber-600" />
          )}
          Reviewed {adjudicatedCount} / {critiques.length} critiques.
        </p>
        <Button onClick={handleCompleteReview} disabled={isPending || !allAdjudicated}>
          {isPending ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <Check className="mr-2 h-4 w-4" />
          )}
          Complete Review and Continue
        </Button>
      </CardFooter>
    </Card>
  );
};

interface CritiqueItemProps {
  critique: AvlCritique;
  decision?: AvlAdjudication;
  onChange: (decision: AvlAdjudication) => void;
  disabled: boolean;
}

const CritiqueItem = ({ critique, decision, onChange, disabled }: CritiqueItemProps) => {
  return (
    <div className="flex flex-col gap-4 rounded-lg border bg-background p-4 shadow-sm transition-colors duration-200 hover:border-primary/50 md:flex-row">
      <div className="mt-1 flex-shrink-0">
        <ShieldAlert className="h-6 w-6 text-amber-600 dark:text-amber-500" />
      </div>
      <div className="flex-1 space-y-2">
        <p className="text-sm font-medium text-foreground leading-relaxed">{critique.critique}</p>
        {critique.suggestion ? (
          <div className="rounded bg-muted/50 p-2 text-xs text-muted-foreground">
            <p className="font-semibold">Suggestion:</p>
            <p className="italic">{critique.suggestion}</p>
          </div>
        ) : null}
      </div>
      <div className="flex-shrink-0 pt-4 md:w-64 md:border-l md:pl-4 md:pt-0">
        <RadioGroup
          value={decision}
          onValueChange={(value) => onChange(value as AvlAdjudication)}
          className="flex flex-col gap-3"
          disabled={disabled}
        >
          <div className="flex items-center space-x-3">
            <RadioGroupItem value="ACCEPT" id={`accept-${critique.id}`} />
            <Label
              htmlFor={`accept-${critique.id}`}
              className="flex cursor-pointer items-center gap-2 text-sm font-medium text-red-600 dark:text-red-500"
            >
              <ThumbsDown className="h-4 w-4" />
              Accept Critique (Revise)
            </Label>
          </div>
          <div className="flex items-center space-x-3">
            <RadioGroupItem value="REJECT" id={`reject-${critique.id}`} />
            <Label
              htmlFor={`reject-${critique.id}`}
              className="flex cursor-pointer items-center gap-2 text-sm font-medium text-green-600 dark:text-green-500"
            >
              <ThumbsUp className="h-4 w-4" />
              Reject Critique (Keep)
            </Label>
          </div>
        </RadioGroup>
      </div>
    </div>
  );
};
