"""Update workflow models for multitenancy and manual editing

Revision ID: 3a5b6c7d8e9f
Revises: a9c8b7d6e5f4
Create Date: 2024-05-23 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5b6c7d8e9f'
down_revision = 'a9c8b7d6e5f4'
branch_labels = None
depends_on = None

# Define Enum type for database operations
version_source_enum = sa.Enum('AI_GENERATED', 'MANUALLY_EDITED', name='versionsource')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the new enum type in the database before using it in a column.
    version_source_enum.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table('node_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', version_source_enum, server_default='AI_GENERATED', nullable=False))
        batch_op.add_column(sa.Column('based_on_version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f('fk_node_versions_based_on_version_id_node_versions'), 
            'node_versions', ['based_on_version_id'], ['id']
        )

    with op.batch_alter_table('node_instances', schema=None) as batch_op:
        # Add the new user_id column as non-nullable, enforcing data integrity for new records.
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_node_instances_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_node_instances_user_id_users'), 
            'users', ['user_id'], ['id']
        )

    with op.batch_alter_table('workflow_instances', schema=None) as batch_op:
        # Add the new user_id column as non-nullable.
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # Alter the existing project_id column to be non-nullable, completing the data model refactoring.
        batch_op.alter_column('project_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_workflow_instances_user_id_users'), 
            'users', ['user_id'], ['id']
        )
        batch_op.drop_column('external_data_refs')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('workflow_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_data_refs', sa.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_workflow_instances_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_workflow_instances_user_id'))
        batch_op.drop_column('user_id')
        batch_op.alter_column('project_id', existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table('node_instances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_node_instances_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_node_instances_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('node_versions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_node_versions_based_on_version_id_node_versions'), type_='foreignkey')
        batch_op.drop_column('based_on_version_id')
        batch_op.drop_column('source')

    # Drop the enum type from the database.
    version_source_enum.drop(op.get_bind(), checkfirst=False)
    
    # ### end Alembic commands ###
