"""Add User and UserSettings models

Revision ID: d78b8a3e7d5e
Revises: f8a3a2a1b0c9
Create Date: 2024-05-22 10:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78b8a3e7d5e'
down_revision = 'f8a3a2a1b0c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('EN', 'ZH', name='supportedlanguage'), nullable=False),
    sa.Column('theme', sa.Enum('LIGHT', 'DARK', name='interfacetheme'), nullable=False),
    sa.Column('hitl_profile', sa.Enum('NOVICE', 'EXPERIENCED', 'EXPERT', name='hitlprofile'), nullable=False),
    sa.Column('thinking_depth', sa.Enum('INSTANT', 'MEDIUM', 'HEAVY', name='thinkingdepth'), nullable=False),
    sa.Column('llm_model_name', sa.String(), nullable=True),
    sa.Column('llm_base_url', sa.String(), nullable=True),
    sa.Column('llm_api_key_encrypted', sa.String(), nullable=True),
    sa.Column('e2b_api_key_encrypted', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

