"""Initial migration

Revision ID: f8a3a2a1b0c9
Revises: 
Create Date: 2024-05-22 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.ext.mutable import MutableDict, MutableList


# revision identifiers, used by Alembic.
revision = "f8a3a2a1b0c9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("status", sa.Enum("RUNNING", "COMPLETED", name="workflowstatus"), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("external_data_refs", MutableDict.as_mutable(sa.JSON()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflow_instances_id"), "workflow_instances", ["id"], unique=False)
    op.create_index(op.f("ix_workflow_instances_name"), "workflow_instances", ["name"], unique=False)

    op.create_table(
        "node_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_instance_id", sa.Integer(), nullable=False),
        sa.Column("definition_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("node_type", sa.Enum("STANDARD", "GENERATOR", name="nodetype"), nullable=False),
        sa.Column("hitl_mode", sa.Enum("VARL", "SCA", "AVL", name="hitlmode"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "EXECUTING",
                "AWAITING_HITL_APPROVAL",
                "COMPLETED",
                "FAILED",
                name="nodestatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "current_stage",
            sa.Enum(
                "NOT_STARTED",
                "INITIALIZING",
                "PROCESSING",
                "GENERATING_OUTPUTS",
                "AWAITING_REVIEW",
                "COMPLETED",
                "FAILED",
                name="executionstage",
            ),
            nullable=True,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("active_version_id", sa.Integer(), nullable=True),
        sa.Column("dependencies", MutableDict.as_mutable(sa.JSON()), nullable=True),
        sa.Column("external_inputs", MutableList.as_mutable(sa.JSON()), nullable=True),
        sa.Column("phase_id", sa.String(), nullable=False),
        sa.Column("task_group_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["workflow_instance_id"], ["workflow_instances.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_node_instances_definition_id"), "node_instances", ["definition_id"], unique=False)
    op.create_index(op.f("ix_node_instances_id"), "node_instances", ["id"], unique=False)
    op.create_index(op.f("ix_node_instances_phase_id"), "node_instances", ["phase_id"], unique=False)
    op.create_index(op.f("ix_node_instances_task_group_id"), "node_instances", ["task_group_id"], unique=False)

    op.create_table(
        "node_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_instance_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("output_data", MutableDict.as_mutable(sa.JSON()), nullable=True),
        sa.Column("raw_generated_output", MutableDict.as_mutable(sa.JSON()), nullable=True),
        sa.Column("input_dependencies", MutableDict.as_mutable(sa.JSON()), nullable=False),
        sa.Column("hitl_history", MutableList.as_mutable(sa.JSON()), nullable=False),
        sa.Column("llm_model_name", sa.String(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("summary", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(["node_instance_id"], ["node_instances.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_instance_id", "version_number", name="_node_version_uc"),
    )
    op.create_index(op.f("ix_node_versions_id"), "node_versions", ["id"], unique=False)

    op.create_table(
        "temporary_execution_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_instance_id", sa.Integer(), nullable=False),
        sa.Column("output_data", MutableDict.as_mutable(sa.JSON()), nullable=True),
        sa.Column("input_dependencies", MutableDict.as_mutable(sa.JSON()), nullable=False),
        sa.Column("accumulated_hitl_interactions", MutableList.as_mutable(sa.JSON()), nullable=False),
        sa.Column("llm_model_name", sa.String(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["node_instance_id"], ["node_instances.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_instance_id"),
    )
    op.create_index(
        op.f("ix_temporary_execution_results_id"), "temporary_execution_results", ["id"], unique=False
    )

    # Add the foreign key for the circular dependency after both tables are created
    op.create_foreign_key(
        "fk_node_instances_active_version_id_node_versions",
        "node_instances",
        "node_versions",
        ["active_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_node_instances_active_version_id_node_versions", "node_instances", type_="foreignkey"
    )
    op.drop_index(op.f("ix_temporary_execution_results_id"), table_name="temporary_execution_results")
    op.drop_table("temporary_execution_results")
    op.drop_index(op.f("ix_node_versions_id"), table_name="node_versions")
    op.drop_table("node_versions")
    op.drop_index(op.f("ix_node_instances_task_group_id"), table_name="node_instances")
    op.drop_index(op.f("ix_node_instances_phase_id"), table_name="node_instances")
    op.drop_index(op.f("ix_node_instances_id"), table_name="node_instances")
    op.drop_index(op.f("ix_node_instances_definition_id"), table_name="node_instances")
    op.drop_table("node_instances")
    op.drop_index(op.f("ix_workflow_instances_name"), table_name="workflow_instances")
    op.drop_index(op.f("ix_workflow_instances_id"), table_name="workflow_instances")
    op.drop_table("workflow_instances")
    # ### end Alembic commands ###
