# A generic Alembic configuration file.
# https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-config-file

[alembic]
# Path to the migration script directory.
# The path is relative to the location of this ini file.
script_location = alembic

# A file name for the log output, or 'stdout' to log to the console.
# logging_file_name = alembic.log

# The name of the alembic version table.
# version_table = alembic_version


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
