import { z } from "zod";
import { JsonObjectSchema } from "./common.model";

// --- Centralized HITL Data Models ---

// --- SCA (Strategic Choice Architecture) Models (Design Doc H3.1) ---

/**
 * Represents a single candidate option in SCA (API 5.1.1 Example).
 */
export const SCACandidateSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  // The actual content/details of the candidate. Can be a markdown string or a structured object.
  content: z.union([JsonObjectSchema, z.string()]).optional().nullable(),
  // Optional summary provided by the LLM
  summary: z.string().optional().nullable(),
}).passthrough(); // Allow extra fields added by LLM (e.g., scores, metadata)
export type SCACandidate = z.infer<typeof SCACandidateSchema>;

/**
 * The structure of output_data when hitl_mode is SCA.
 */
export const SCAOutputDataSchema = z.object({
  // List of candidates. We allow 0 candidates to handle that case gracefully in the UI.
  candidates: z.array(SCACandidateSchema),
  comparative_analysis: z.string().nullable().optional(),
}).passthrough();
export type SCAOutputData = z.infer<typeof SCAOutputDataSchema>;

/**
 * The structure of interaction_data submitted for SCA (API 5.3).
 */
export const SCAInteractionDataSchema = z.object({
  // The IDs of the selected candidate(s).
  selected_ids: z.array(z.string()),
});
export type SCAInteractionData = z.infer<typeof SCAInteractionDataSchema>;

/**
 * Form schema for the SCA Panel (using React Hook Form).
 * Assumes single selection (RadioGroup) for strategic choice.
 */
export const SCAPanelFormSchema = z.object({
    // The ID of the selected candidate. The requirement is handled dynamically in the panel based on candidate existence.
    selected_id: z.string().optional(),
});
export type SCAPanelFormValues = z.infer<typeof SCAPanelFormSchema>;


// --- AVL (Adversarial Validation Loop) Models (Design Doc H3.2) ---
// (Task 20 Implementation)

// AVL Enums
export const AVLSeverityEnum = z.enum(["Low", "Medium", "High", "Critical"]);
export type AVLSeverity = z.infer<typeof AVLSeverityEnum>;

export const AVLDecisionEnum = z.enum(["Accepted", "Rejected"]);
export type AVLDecision = z.infer<typeof AVLDecisionEnum>;

/**
 * Represents a single critique generated by the AI Critic.
 */
export const AVLCritiqueSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1), // Markdown content
  severity: AVLSeverityEnum.optional().nullable(),
  // Allow extra fields (e.g., suggested_action, category)
}).passthrough();
export type AVLCritique = z.infer<typeof AVLCritiqueSchema>;

/**
 * The structure of output_data when hitl_mode is AVL.
 */
export const AVLOutputDataSchema = z.object({
  // List of critiques. 0 critiques means validation passed automatically.
  critiques: z.array(AVLCritiqueSchema),
  validation_summary: z.string().nullable().optional(),
}).passthrough();
export type AVLOutputData = z.infer<typeof AVLOutputDataSchema>;

/**
 * Represents the user's adjudication for a single critique (API 5.3).
 */
export const AVLAdjudicationSchema = z.object({
  critique_id: z.string().min(1),
  decision: AVLDecisionEnum,
  comment: z.string().nullable().optional(),
});
export type AVLAdjudication = z.infer<typeof AVLAdjudicationSchema>;

/**
 * The structure of interaction_data submitted for AVL (API 5.3).
 */
export const AVLInteractionDataSchema = z.object({
  adjudication: z.array(AVLAdjudicationSchema),
});
export type AVLInteractionData = z.infer<typeof AVLInteractionDataSchema>;

/**
 * Form schema shape for the AVL Panel (using React Hook Form).
 * Manages a map of adjudications keyed by critique ID.
 */
// Schema for a single item within the form. Decision is required.
const AVLAdjudicationFormItemSchema = z.object({
    decision: AVLDecisionEnum,
    // Ensure comment can be optional string or null/undefined for RHF compatibility
    comment: z.string().optional().nullable(),
});

// The overall form shape.
export const AVLPanelFormSchema = z.object({
  // Keys are critique IDs (strings). Values are the adjudication details.
  // The validation that ALL required critiques (based on input data)
  // are present in this record is handled dynamically via .refine() in the AVLPanel component.
  adjudications: z.record(
    z.string(),
    AVLAdjudicationFormItemSchema
  ).optional(), // optional() because the map might be empty initially or if there are 0 critiques.
});
export type AVLPanelFormValues = z.infer<typeof AVLPanelFormSchema>;

// --- VARL (Verification and Approval Loop) Models (Design Doc H3.3) ---
// VARL typically doesn't require specific complex structures beyond the main output_data.

